/*
 * Demo of the DrawingManager on a daily SPY chart (demo/public): a
 * TradingView-style left toolbar with the tools under TradingView's groups
 * (demo/tool-groups.ts, generated by docs/tools_md.py), magnet, keep
 * drawing, remove all, a selection bar (Anchor drawing, delete), an inline
 * text / table cell editor and JSON export / import as files.
 * `window.dm` / `window.chart` / `window.series` / `window.lwcd` (the library
 * module) for scripted checks; `window.autoText` answers the text editor
 * request without the editor.
 */
import { CandlestickSeries, createChart, type Time } from "lightweight-charts";
import * as lwcd from "../src";
import { cacheImage, decodeImage, DrawingManager, isAnchorable, VERSION, type Drawing, type DrawingKind, type MagnetMode } from "../src";
import { ICONS } from "./icons";
import { TOOL_COUNT, TOOL_GROUPS, type ToolEntry } from "./tool-groups";

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const el = <K extends keyof HTMLElementTagNameMap>(tag: K, cls?: string, html?: string) => {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (html != null) e.innerHTML = html;
  return e;
};

/** Tool entry per kind (title, placement) from the TradingView groups. */
const TOOLS = new Map<string, ToolEntry & { group: string }>();
for (const g of TOOL_GROUPS) for (const s of g.sections) for (const t of s.tools) TOOLS.set(t.kind, { ...t, group: g.title });
TOOLS.set("font-icon", { kind: "font-icon", title: "Emoji", placement: "1 click", group: "emoji" });

/** A few Unicode emojis for the font-icon tool (TradingView Icons group). */
const EMOJIS = ["🚀", "📈", "📉", "💰", "💵", "🔥", "⚡", "🎯", "✅", "❌", "⚠️", "⭐", "🔔", "⏰", "💡", "📌",
  "🐂", "🐻", "🐳", "🦄", "👍", "👎", "👀", "💎", "😀", "😎", "🤔", "😱", "🤯", "🥳", "😭", "🙏"];

async function main() {
  const csv = await (await fetch(`${import.meta.env.BASE_URL}SPY.csv`)).text();
  const rows = csv.trim().split("\n").slice(1).map((l) => l.split(",").map(Number));
  const data = rows.slice(-600).map(([t, o, h, l, c]) => ({ time: t as Time, open: o, high: h, low: l, close: c }));
  const chart = createChart($("chart"), {
    autoSize: true,
    layout: { background: { color: "#0f0f0f" }, textColor: "#dbdbdb", fontFamily: getComputedStyle(document.body).fontFamily },
    grid: { vertLines: { color: "#1f1f1f" }, horzLines: { color: "#1f1f1f" } },
    rightPriceScale: { borderColor: "#2e2e2e" },
    timeScale: { borderColor: "#2e2e2e", rightOffset: 12 },
    crosshair: { vertLine: { color: "#9598a1", labelBackgroundColor: "#363a45" }, horzLine: { color: "#9598a1", labelBackgroundColor: "#363a45" } },
  });
  const series = chart.addSeries(CandlestickSeries, { upColor: "#089981", downColor: "#f23645", borderVisible: false, wickUpColor: "#089981", wickDownColor: "#f23645" });
  series.setData(data);
  chart.timeScale().setVisibleLogicalRange({ from: data.length - 160, to: data.length + 12 });
  const dm = new DrawingManager(chart, series, { magnet: "off" });
  Object.assign(window, { dm, chart, series, lwcd });

  $("version").textContent = `v${VERSION}`;
  $("github").innerHTML = ICONS.github;
  $("export").innerHTML = `${ICONS.download}Export`;
  $("import").innerHTML = `${ICONS.upload}Import`;

  // ---- status line
  let note = "";
  let noteTimer = 0;
  const hint = $("hint");
  const flash = (s: string) => {
    note = s;
    clearTimeout(noteTimer);
    noteTimer = window.setTimeout(() => { note = ""; refreshHint(); }, 3000);
    refreshHint();
  };
  const refreshHint = () => {
    if (note) { hint.innerHTML = note; return; }
    const k = dm.tool();
    const t = k ? TOOLS.get(k) : undefined;
    if (t) hint.innerHTML = `<b>${t.title}</b>: ${t.placement} on the chart. <kbd>Esc</kbd> cancels. <kbd>Shift</kbd> keeps 45° steps.`;
    else if (dm.selection().length) hint.innerHTML = `Drag the points or the body to edit. <kbd>Ctrl</kbd> + drag clones, <kbd>Del</kbd> removes, <kbd>Esc</kbd> deselects.`;
    else hint.innerHTML = `Pick a tool in the left toolbar, then click on the chart. Click a drawing to select it.`;
  };
  const refreshCount = () => {
    const n = dm.drawings().length;
    $("count").textContent = `${n} drawing${n === 1 ? "" : "s"} · ${TOOL_COUNT} tools`;
  };
  dm.on("change", refreshCount);
  refreshCount();

  // ---- flyout menus
  const flyout = $("flyout");
  let openBtn: HTMLElement | null = null;
  const closeFlyout = () => {
    flyout.hidden = true;
    openBtn?.classList.remove("open");
    openBtn = null;
  };
  const openFlyout = (btn: HTMLElement, fill: (f: HTMLElement) => void) => {
    if (openBtn === btn) return closeFlyout();
    closeFlyout();
    flyout.replaceChildren();
    fill(flyout);
    flyout.hidden = false;
    openBtn = btn;
    btn.classList.add("open");
    const main = $("main").getBoundingClientRect();
    const b = btn.getBoundingClientRect();
    flyout.style.left = `${b.right - main.left + 6}px`;
    const top = Math.max(6, Math.min(b.top - main.top, main.height - flyout.offsetHeight - 6));
    flyout.style.top = `${top}px`;
  };
  document.addEventListener("pointerdown", (e) => {
    if (flyout.hidden) return;
    const t = e.target as Node;
    if (!flyout.contains(t) && !openBtn?.contains(t)) closeFlyout();
  });
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") closeFlyout(); });
  const item = (label: string, hintText: string, onClick: () => void, active = false) => {
    const b = el("button", `fly-item${active ? " active" : ""}`);
    b.append(el("span", "", label));
    if (hintText) b.append(el("span", "hint", hintText));
    b.onclick = () => { closeFlyout(); onClick(); };
    return b;
  };

  // ---- left toolbar
  const rail = $("rail");
  const railBtn = (icon: string, title: string, more = false) => {
    const b = el("button", "tool", icon);
    b.title = title;
    if (more) b.append(el("span", "more"));
    rail.append(b);
    return b;
  };
  const sep = () => rail.append(el("div", "rail-sep"));

  const imageFile = $<HTMLInputElement>("imageFile");
  const arm = (kind: string) => {
    if (kind === "image") { imageFile.click(); return; }
    dm.setTool(kind as DrawingKind);
  };

  const cursorBtn = railBtn(ICONS.cursor, "Cursor");
  cursorBtn.onclick = () => { closeFlyout(); dm.setTool(null); };
  const groupBtns = new Map<string, HTMLElement>();
  for (const g of TOOL_GROUPS) {
    const b = railBtn(ICONS[g.title] ?? ICONS.cursor, g.title, true);
    groupBtns.set(g.title, b);
    b.onclick = () => openFlyout(b, (f) => {
      for (const s of g.sections) {
        f.append(el("div", "fly-head", s.header ?? g.title));
        for (const t of s.tools) f.append(item(t.title, t.placement, () => arm(t.kind), dm.tool() === t.kind));
      }
    });
  }
  const emojiBtn = railBtn(ICONS.emoji, "Emojis", true);
  groupBtns.set("emoji", emojiBtn);
  emojiBtn.onclick = () => openFlyout(emojiBtn, (f) => {
    f.append(el("div", "fly-head", "Emojis"));
    const grid = el("div", "emoji-grid");
    for (const e of EMOJIS) {
      const b = el("button", "", e);
      b.onclick = () => { closeFlyout(); dm.setTool("font-icon" as DrawingKind, { glyph: e }); };
      grid.append(b);
    }
    f.append(grid);
  });
  sep();

  // Magnet: the button toggles, the corner arrow picks weak / strong (TV).
  let magnetMode: Exclude<MagnetMode, "off"> = "weak";
  let magnetOn = false;
  const magnetBtn = railBtn(ICONS.magnet, "Magnet mode", true);
  const setMagnet = (on: boolean) => {
    magnetOn = on;
    dm.setMagnet(on ? magnetMode : "off");
    magnetBtn.classList.toggle("active", on);
    magnetBtn.title = `Magnet mode: ${on ? `${magnetMode} magnet` : "off"}`;
  };
  magnetBtn.onclick = (e) => {
    if ((e.target as HTMLElement).classList.contains("more")) {
      openFlyout(magnetBtn, (f) => {
        f.append(el("div", "fly-head", "Magnet"));
        f.append(item("Weak magnet", "snaps near OHLC", () => { magnetMode = "weak"; setMagnet(true); }, magnetOn && magnetMode === "weak"));
        f.append(item("Strong magnet", "always snaps to OHLC", () => { magnetMode = "strong"; setMagnet(true); }, magnetOn && magnetMode === "strong"));
      });
      return;
    }
    closeFlyout();
    setMagnet(!magnetOn);
  };
  const keepBtn = railBtn(ICONS.keep, "Keep drawing");
  let keep = false;
  keepBtn.onclick = () => {
    keep = !keep;
    dm.setStayInDrawingMode(keep);
    keepBtn.classList.toggle("active", keep);
  };
  const trashBtn = railBtn(ICONS.trash, "Remove drawings", true);
  trashBtn.onclick = () => openFlyout(trashBtn, (f) => {
    const n = dm.drawings().length;
    f.append(item(n ? `Remove ${n} drawing${n === 1 ? "" : "s"}` : "No drawings to remove", "", () => { if (n) dm.clear(); }));
  });

  const refreshRail = () => {
    const k = dm.tool();
    const g = k ? TOOLS.get(k)?.group : undefined;
    cursorBtn.classList.toggle("active", !k);
    for (const [title, b] of groupBtns) {
      b.classList.toggle("active", title === g);
      if (title === g) b.title = `${title}: ${TOOLS.get(k!)!.title}`;
    }
  };
  dm.on("tool", () => { refreshRail(); refreshHint(); });
  refreshRail();
  refreshHint();

  // ---- image (Annotation tools / Content): the host reads the file and
  // puts it in the core image cache under a name; the drawing stores it.
  imageFile.onchange = async () => {
    const f = imageFile.files?.[0];
    if (!f) return;
    const url = await new Promise<string>((res) => { const r = new FileReader(); r.onload = () => res(String(r.result)); r.readAsDataURL(f); });
    const img = await decodeImage(url);
    const name = `${Date.now().toString(36)}-${f.name}`;
    cacheImage(name, img);
    dm.addImage({ name, width: img.width, height: img.height });
    imageFile.value = "";
  };

  // ---- selection bar: tool name, Anchor drawing (Text, Pin, Table), delete
  const selbar = $("selbar");
  const refreshSelbar = () => {
    const ds = dm.selection().map((id) => dm.get(id)).filter((d): d is Drawing => !!d);
    selbar.hidden = ds.length === 0;
    if (!ds.length) return;
    selbar.replaceChildren();
    const one = ds.length === 1 ? ds[0] : undefined;
    selbar.append(el("span", "title", one ? TOOLS.get(one.kind)?.title ?? one.kind : `${ds.length} drawings`));
    if (one && isAnchorable(one.kind)) {
      const a = el("button", `tool${one.anchored ? " active" : ""}`, ICONS.anchor);
      a.title = one.anchored ? "Anchored: keeps its place on the pane (click to unanchor)" : "Anchor drawing: keep its place on the pane when the chart scrolls";
      a.onclick = () => dm.toggleAnchored(one.id);
      selbar.append(a);
    }
    const del = el("button", "tool", ICONS.trash);
    del.title = "Remove";
    del.onclick = () => { for (const d of ds) if (!d.locked) dm.remove(d.id); };
    selbar.append(del);
  };
  dm.on("selection", () => { refreshSelbar(); refreshHint(); });
  dm.on("update", refreshSelbar);
  dm.on("remove", refreshSelbar);

  // ---- inline editor for text tools and table cells
  const editor = $<HTMLTextAreaElement>("editor");
  let commit: ((text: string) => void) | null = null;
  let cancel: (() => void) | null = null;
  // The manager asks for the editor inside the mouse press: open it after
  // the release, else the release moves the focus away and closes it.
  let pressed = false;
  window.addEventListener("pointerdown", () => { pressed = true; }, true);
  window.addEventListener("pointerup", () => { pressed = false; }, true);
  const afterRelease = (fn: () => void) => {
    if (!pressed) return fn();
    window.addEventListener("pointerup", () => setTimeout(fn), { once: true });
  };
  const openEditor = (left: number, top: number, width: number, value: string, onCommit: (t: string) => void, onCancel: () => void) => {
    commit = (t) => { if (t !== value) onCommit(t); else onCancel(); };
    cancel = onCancel;
    const wrap = $("chartWrap").getBoundingClientRect();
    editor.style.left = `${Math.max(4, Math.min(left, wrap.width - 180))}px`;
    editor.style.top = `${Math.max(4, Math.min(top, wrap.height - 60))}px`;
    editor.style.width = `${Math.max(180, width)}px`;
    editor.value = value;
    editor.hidden = false;
    editor.focus();
    editor.select();
  };
  const closeEditor = (ok: boolean) => {
    if (editor.hidden) return;
    editor.hidden = true;
    const c = commit;
    const x = cancel;
    commit = cancel = null;
    if (ok) c?.(editor.value);
    else x?.();
  };
  editor.addEventListener("keydown", (e) => {
    e.stopPropagation();
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); closeEditor(true); }
    else if (e.key === "Escape") { e.preventDefault(); closeEditor(false); }
  });
  editor.addEventListener("blur", () => closeEditor(true));
  const autoText = () => (window as unknown as { autoText?: string }).autoText;

  dm.on("textEdit", (d, p) => {
    const setText = (text: string) => { const cur = dm.get(d.id); if (cur && cur.text !== text) dm.update({ ...cur, text }); };
    const auto = autoText();
    if (auto != null) return setText(auto);
    afterRelease(() => openEditor(p.x + 8, p.y - 16, 0, d.text ?? "", setText, () => {}));
  });
  dm.on("tableEdit", (d, cell, box) => {
    const auto = autoText();
    if (auto != null) { dm.setTableCellText(d.id, cell, auto); dm.endTableEdit(); return; }
    const cells = (d.style as { tableCells?: string[][] }).tableCells;
    afterRelease(() => openEditor(box.left, box.top, box.width, cells?.[cell[0]]?.[cell[1]] ?? "", (t) => { dm.setTableCellText(d.id, cell, t); dm.endTableEdit(); }, () => dm.endTableEdit()));
  });

  // ---- export / import as JSON files
  $("export").onclick = () => {
    const n = dm.drawings().length;
    if (!n) return flash("Nothing to export: draw something first.");
    const url = URL.createObjectURL(new Blob([dm.exportJSON()], { type: "application/json" }));
    const a = el("a");
    a.href = url;
    a.download = `drawings-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    flash(`Exported <b>${n}</b> drawing${n === 1 ? "" : "s"} to ${a.download}.`);
  };
  const importFile = $<HTMLInputElement>("importFile");
  $("import").onclick = () => importFile.click();
  importFile.onchange = async () => {
    const f = importFile.files?.[0];
    importFile.value = "";
    if (!f) return;
    try {
      const n = dm.importJSON(await f.text());
      flash(`Imported <b>${n}</b> drawing${n === 1 ? "" : "s"} from ${f.name}.`);
    } catch (err) {
      flash(`Could not read ${f.name}: ${(err as Error).message}`);
    }
  };
}

void main();
