"""Generate docs/TOOLS.md and demo/tool-groups.ts: the tools of the drawing
core (src/tv/specs.ts OVERLAY_SPECS) under TradingView's toolbar groups and
names (OpenTrader src/data/drawing-toolbar.ts, captured from TradingView
Desktop).

python docs/tools_md.py [<opentrader drawing-toolbar.ts>]
(default: ../opentrader/src/data/drawing-toolbar.ts, run from the repo root)"""
import json
import re
import sys

toolbar = sys.argv[1] if len(sys.argv) > 1 else '../opentrader/src/data/drawing-toolbar.ts'
specs_src = open('src/tv/specs.ts', encoding='utf8').read()
tb = open(toolbar, encoding='utf8').read()

# Spec per kind: point count and placement flags.
m = re.search(r'OVERLAY_SPECS[^=]*=\s*\{', specs_src)
specs = {}
entries = []
buf = None
for ln in specs_src[m.end():].split('\n'):
    # An entry starts with `  "kind": {` and ends when its braces balance
    # (one line or several).
    if buf is None:
        if not re.match(r'\s{2}"?[a-z0-9-]+"?: \{', ln):
            continue
        buf, depth = ln, ln.count('{') - ln.count('}')
    else:
        buf += ' ' + ln.strip()
        depth += ln.count('{') - ln.count('}')
    if depth <= 0:
        entries.append(buf)
        buf = None
for line in entries:
    k = re.match(r'\s{2}"?([a-z0-9-]+)"?: \{\s*kind:', line)
    if not k:
        continue
    pc = re.search(r'pointCount: (\d+)', line)
    specs[k.group(1)] = {
        'points': int(pc.group(1)) if pc else None,
        'variable': 'variableLength: true' in line,
        'freehand': 'freehand: true' in line,
        'text': 'textEditable: true' in line,
        'hotkey': (re.search(r'hotkey: "([^"]+)"', line) or [None, None])[1],
    }

# TradingView groups / sections / tools in toolbar order.
rows = []
group = None
section = None
for line in tb.split('\n'):
    g = re.match(r'\s{4}title: "([^"]+)",', line)
    if g:
        group = g.group(1)
        section = None
        continue
    h = re.match(r'\s+header: (?:"([^"]+)"|null),', line)
    if h:
        section = h.group(1)
        continue
    t = re.search(r'\{ id: "([a-z0-9-]+)", title: "([^"]+)"', line)
    if t and t.group(1) in specs:
        rows.append((group, section, t.group(1), t.group(2)))

listed = {r[2] for r in rows}
missing = sorted(set(specs) - listed)


def placement(s):
    if s['freehand']:
        return 'press, drag, release'
    if s['variable']:
        return f"clicks (min {s['points']}), double-click or click the last point to finish"
    n = s['points']
    return f"{n} click{'s' if n != 1 else ''}" + (' + text' if s['text'] else '')


out = ['# Drawing tools', '',
       'Generated by `docs/tools_md.py` from the drawing core (`src/tv/specs.ts`',
       '`OVERLAY_SPECS`) and the TradingView toolbar names / groups (OpenTrader',
       '`src/data/drawing-toolbar.ts`, captured from TradingView Desktop).', '',
       f'{len(specs)} tools. `kind` is the value for `DrawingManager.setTool` and',
       'the `kind` of a saved drawing.', '']
cur = None
for g, sec, kind, title in rows:
    head = f'{g} / {sec}' if sec else g
    if head != cur:
        out += ['', f'## {head}', '', '| Tool | kind | Placement | Hotkey |', '|---|---|---|---|']
        cur = head
    s = specs[kind]
    out.append(f"| {title} | `{kind}` | {placement(s)} | {s['hotkey'] or ''} |")
if missing:
    out += ['', '## Not in the TradingView toolbar', '', '| kind | Placement |', '|---|---|']
    out += [f"| `{k}` | {placement(specs[k])} |" for k in missing]
open('docs/TOOLS.md', 'w', encoding='utf8', newline='\n').write('\n'.join(out) + '\n')

# The same groups for the demo toolbar.
groups = []
for g, sec, kind, title in rows:
    if not groups or groups[-1]['title'] != g:
        groups.append({'title': g, 'sections': []})
    secs = groups[-1]['sections']
    if not secs or secs[-1]['header'] != sec:
        secs.append({'header': sec, 'tools': []})
    secs[-1]['tools'].append({'kind': kind, 'title': title, 'placement': placement(specs[kind])})
ts = ['/* Generated by docs/tools_md.py (TradingView toolbar groups of the core',
      ' * tools). Do not edit. */',
      'export type ToolEntry = { kind: string; title: string; placement: string };',
      'export type ToolGroup = { title: string; sections: { header: string | null; tools: ToolEntry[] }[] };',
      f'export const TOOL_COUNT = {len(specs)};',
      'export const TOOL_GROUPS: ToolGroup[] = [']
for grp in groups:
    ts.append(f'  {{ title: {json.dumps(grp["title"])}, sections: [')
    for sec in grp['sections']:
        ts.append(f'    {{ header: {json.dumps(sec["header"])}, tools: [')
        for t in sec['tools']:
            ts.append(f'      {{ kind: {json.dumps(t["kind"])}, title: {json.dumps(t["title"])}, placement: {json.dumps(t["placement"])} }},')
        ts.append('    ] },')
    ts.append('  ] },')
ts.append('];')
open('demo/tool-groups.ts', 'w', encoding='utf8', newline='\n').write('\n'.join(ts) + '\n')
print(f'{len(rows)} tools in groups, {len(missing)} outside: {missing}')
